<a href="https://colab.research.google.com/github/SamuilMladenov/LearnPyTorch/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals Tutorial

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Into to tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#gets tensor back as Python int
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7, 7])

vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                        [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random Tensors

Random tensors are important because the may many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with  random numbers -> look at data -> update random numbers -> look at data -> update radndom numbers`

In [ ]:
# Create a ranodm tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8345, 0.5520, 0.7423, 0.5958],
        [0.3205, 0.1614, 0.6176, 0.2079],
        [0.1644, 0.0912, 0.0912, 0.9587]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random ensor with simular shape of an image
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # hight, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [ ]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Create a tensors-like (we have a tensor that we want to mimic it's shape. zeros_like makes a tensor-like abject that takes a shape and makes it all zeroes)
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None  # what datatype is the tensor (e.g. float32, float64)
                                              , device=None # what device the tensor is on (e.g. "cpu", "cuda")
                                              , requires_grad=False) # Whether or nor to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16) #u can also use .half
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
multiply_tensors = float_16_tensor * float_32_tensor
multiply_tensors


tensor([ 9., 36., 81.])

In [ ]:
multiply_tensors.dtype

torch.float32

### Getting Information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor we use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor we can use `tensor.shape`
3. Tensors not on the right device - to get the device from a tensor we can use `tensor.device`

In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1856, 0.8904, 0.5705, 0.8482],
        [0.9754, 0.0085, 0.8552, 0.9252],
        [0.2080, 0.9553, 0.1309, 0.9599]])

In [ ]:
# Find out details about some_tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [ ]:
# Exercise on changing some attributes and finding their details
exercise_tensor = torch.rand(size=(4, 5), dtype=torch.float16, device=None)
print(exercise_tensor)
print(f"Datatype of tensor: {exercise_tensor.dtype}")
print(f"Shape of tensor: {exercise_tensor.shape}")
print(f"Device of tensor: {exercise_tensor.device}")

tensor([[0.3364, 0.6606, 0.5527, 0.0327, 0.1226],
        [0.7871, 0.9580, 0.6436, 0.9473, 0.9302],
        [0.8325, 0.1729, 0.2012, 0.9546, 0.1367],
        [0.3638, 0.8472, 0.7202, 0.5630, 0.4697]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([4, 5])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiply
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways to perform multiplication in neural networks and deep learning:

1. Element-wise Multiplication
2. Matrix Multiplication (dot product)


In [ ]:
# Element-wise multiolication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiolication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0

for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 629 µs, sys: 0 ns, total: 629 µs
Wall time: 654 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 34 µs, sys: 0 ns, total: 34 µs
Wall time: 37 µs


tensor(14)

There are two main rules that performing matrix multiplication need to satisfy:

1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` wont work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will also work

2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2) -> (2, 2)`

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code) (it should throw an error)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issue, we can manipulate the shape of one of out tensors using a ***transpose***.

A ***transpose*** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B = tensor_B.T

In [ ]:
torch.mm(tensor_A, tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() func requires a tensor of float 32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
# Find the position in the tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
# Find the position in the tensor that has the maximum value with argmax() -> returns index position of target tensor where the maximum value occurs
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined torch._shape_as_tensor
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack - vertical stack) or side by side (hstack - horizontal stask)
* Squeezing - removes all `1` dimensions from a tensor
* Unsqueezing - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (beause a view of a tensor shares the same mamory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x = torch.arange(1., 10.)

In [ ]:
# Squeeze
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_squeezed = torch.squeeze(x_reshaped)
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_squeezed.shape

torch.Size([9])

In [ ]:
# Unsqueeze
x_unsqueezed = torch.unsqueeze(x_squeezed, dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_unsqueezed.shape

torch.Size([1, 9])

In [ ]:
# Permute

In [ ]:
image_size = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]
permuted_image = image_size.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {image_size.shape}")
print(f"New shape: {permuted_image.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is simular to indexing with NumPy

In [ ]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on out new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0, 0] #same as x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension, dim=2)
x[0][0][0]

tensor(1)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, :, 1] # get akk values of 0th and 1st dimension but only index 1 of the 2nd simension

tensor([[2, 5, 8]])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library

And because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy()`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor

array = np.arange(1.0, 8.0)
transfer_tensor = torch.from_numpy(array) # Important: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise

array, transfer_tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the vale of array, what will this do to `transer_tensor`?

array = array + 1

array, transfer_tensor # no change in `transer_tensor`

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpy array

tensor_to_transfer = torch.ones(7)
transfered_array = tensor_to_transfer.numpy() # Important: when converting from pytorch -> numpy, numpy reflects PyTorch's datatype unless specified otherwise

tensor_to_transfer, transfered_array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to `nummpy`
tensor_to_transfer = tensor_to_transfer + 1

tensor_to_transfer, transfered_array # no change here as well so numoy and pytorch don't share memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out out of random)

In short how a neural network learns

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[8.5024e-01, 1.9995e-01, 9.1950e-01, 9.7759e-01],
        [9.4951e-01, 5.7669e-01, 9.7556e-01, 8.8447e-04],
        [4.4063e-01, 5.8270e-03, 9.0530e-01, 4.7830e-01]])
tensor([[0.4203, 0.4634, 0.3312, 0.6233],
        [0.6615, 0.0303, 0.1402, 0.8190],
        [0.9155, 0.6089, 0.0788, 0.1809]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducable tensors
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computations on numbers, thanks to CUDA + Nvidia hardware + PyTorch working behind the scenes to make everything good

### 1. Getting a GPU

1. Easiest - Use Google Colab to get a free GPU
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

In [ ]:
!nvidia-smi

Mon Jan  8 20:27:55 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [ ]:
#Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code

E.g. run on GPU if available, else default to CPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason why we want out tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (Default on the CPU)
tensor2 = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor2, tensor2.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor2.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Move tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])